# fly.toml app configuration file generated for danfoss-exporter on 2024-05-16T21:26:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "danfoss-exporter"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "rolling"

[env]
  ENV = "production"
